version: "3.8"

services:
  api:
    container_name: "api"
    restart: always
    build: '.'
    env_file: .env
    ports:
      - 10000:10000

  # undrgrnd-server-redis-cache:
  #   container_name: "undrgrnd-server-redis-cache"
  #   image: redis:7-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - docker-sandbox-mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: todos

# volumes:
#   docker-sandbox-mysql-data:


